version: "3.8"

services:
  api:
    build: .
    ports:
      - "3333:3333"
    environment:
      # point at the 'db' service on Mongo's default port
      MONGO_URI: mongodb://db:27017/desafio
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db

  db:
    image: mongo:6
    # expose Mongo's default port so any host can connect
    ports:
      - "27017:27017"
    # bind to 0.0.0.0 so Mongo listens on all network interfaces
    command: ["mongod", "--bind_ip_all"]
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
